---
- name: Playbook de ping 
  hosts: all
  tasks:
    - name: ping test
      raw: ping -c 1 -w 2 {{ DNS1 }}
      delegate_to: localhost
      ignore_errors: true
      register: output1

    - name: ping test
      raw: ping -c 1 -w 2 {{ DNS2 }}
      delegate_to: localhost
      ignore_errors: true
      register: output2

    - set_fact:
        output: "{{ 'ping -c 1 -w 2' + DNS1 + '\n' + output1.stdout + '\n' + 'ping -c 1 -w 2' + DNS2 + '\n' + output2.stdout}}"

    - debug:
        var: output

    - pause:
        minutes: 2
