---
- name: Playbook de ping 
  hosts: all
  tasks:
    - name: ping test
      shell: ping -c 1 -w 2 {{ DNS1 }}
      delegate_to: localhost
      ignore_errors: true
      register: output1

    - name: ping test
      shell: ping -c 1 -w 2 {{ DNS2 }}
      delegate_to: localhost
      ignore_errors: true
      register: output2

    - debug:
        var: output1

    - debug:
        var: output2