galaxy_info:
  author: Henrique Faganello
  namespace: henrique
  description: Developer
  company: IcaroTech
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []

dependencies: []
