---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: henrique-nginx
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    cap_add:
        - SYS_ADMIN
        - SYS_TIME
    pre_build_image: true
provisioner:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
